### PR TITLE
[WIP] Add inspection for deprecated annotations + QuickFix

### PR DESCRIPTION
**Pull request by cedricziel**
This adds an extensionPoint that can provide replacements.

If a replacement is provided, it replaces the import statement.

Also contains an example extension to replace the `@route` annotation.

Could be further expanded to provide a `Configurable` with custom
replacements or further actions such as a custom QuickFix to invoke
compacting the `@method` annotation into the new (old) `@route`
annotation.

#122 should be merged first, since this change relies on it.

### CODE REVIEW

**Comment by cedricziel** [comment]
The last commit added some logic to replace the Annotation with a modified version of itself. I need to adjust it, so it iterates over all `@Route` annotations in the document to transform them.

Back in WIP state.

**Comment by Haehnchen** [comment]
@cedricziel WIP are you ready? i want to do some releases soon :)

**Comment by Haehnchen** [comment]
most work merged; only the replacement class was removed, because it was only support "@Route". Was trying to implement it fully, but then decided to split this feature for later

**Comment by Haehnchen** [comment]
closing this. Deprecation handling is in. But this special replacement for "@Route" looks for me not worth to main.

**Pull request closed without merging**
