### PR TITLE
WI-59872 Provide entry point for properties with '@ORM\Id' annotation

### PR DESCRIPTION
**Pull request by wbars**

### CODE REVIEW

**Comment by wbars** [comment]
https://youtrack.jetbrains.com/issue/WI-59872#focus=Comments-27-4983900.0-0

**Comment by wbars** [comment]
Please feel free to adjust logic if needed.

**Comment by Haehnchen** [comment]
thx, will extend it to all properties

**Comment by Haehnchen** [comment]
pr reverted via https://github.com/Haehnchen/idea-php-annotation-plugin/commit/8b07a7a50938b5c5c71ec552a1570407b2e90235. problem not resolvable via external plugins by this extension point, see youtrack issue.

**Comment by wbars** [comment]
@Haehnchen Please see https://youtrack.jetbrains.com/issue/WI-59872#focus=Comments-27-5525897.0-0 and https://github.com/wbars/phpstorm-entry-point-test

**Pull request merged**
