### PR TITLE
Typo fixed: indention -> intention

### PR DESCRIPTION
**Pull request by King2500**
I think you meant "intention" instead of "indention". ;-)

### CODE REVIEW

**Comment by Haehnchen** [comment]
can you please combine them in one commit?

**Comment by King2500** [comment]
Does this work? Otherwise I can make a fresh pull-request...

**Comment by Haehnchen** [comment]
`git squash` is your friend. otherwise open a new request :)
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by King2500** [comment]
There you go :)

**Pull request merged**
